### ISSUE TITLE
Support decryption of file format version 3.0

### ISSUE THREAD

**Issue by h0nIg** [marnix/synology-decrypt#15]
Hey,

it seems that synology updated their storage format to a newer version: the following code part is failing, saying that the version (3...) does not match. could you take a look at the new format?

https://github.com/marnix/synology-decrypt/blob/master/syndecrypt/core.py#L219

btw: great work, original synology decrypt tool is always failing on huge data sources and support will not help :(

**Comment by marnix** [comment]
@h0nIg Thanks for using my humble hack, and for letting me know it is at one point better than the original!

Thanks for letting me know that this format changed.

I'll try to make some time to look into this within a week or so.

**Comment by marnix** [comment]
To document what I've learned so far: the only difference between version 1.0 and version 3.0 is that the latter always has a new `salt` field containing an 8-byte string (which might be the base64-encoding of an 8-byte array, but I doubt it).

It looks like this salt needs to be used whenever decrypting `enc_key1` (= the session key encrypted with the password) or decrypting a block of data with the session key.

**Comment by marnix** [comment]
Here are two samples of encryption using the salt.  If the algorithm is the same as for format version 1.0, then it is AES-256 in CBC mode, with key+iv as derived from the password by `openssl enc`.

| plaintext | password | salt | ciphertext |
| --- | --- | --- | --- |
| “Just a single line, no newline character at the end...” (4a75737420612073696e676c65206c696e652c206e6f206e65776c696e65 206368617261637465722061742074686520656e642e2e2e) | “buJx9/y9fV” | “DXzp4VKu” (44587a7034564b75 or 0d7ce9e152ae) | 8f7d757c0e46ab0c434ab72b2a70ec71ad49b2284257189365cb4c706751 10a3b98bd95f58bd5eafdccb51020354dc33449b221b45c134180882aa84 739ff78f0213a54a720537785495a84425b0415b |
| “EA23EB5F36B9008AC73498A8FC53884D1D7EFBA052F902F44B44D40409CBC215” (454132334542354633364239303038414337333439384138464335333838 344431443745464241303532463930324634344234344434303430394342 43323135) | “buJx9/y9fV” | “DXzp4VKu” (44587a7034564b75 or 0d7ce9e152ae) | e866e8c3fb7496d6dd5f0d8befd212e351d3558edf7f097bbe5994b38082 3a6b68a9221dc43c53726b767268c4dfc01f92f99383407070ae5622c10c 27003cd4d4bcbda1d4bfbe03f5784f5cc45c95b3 |

So: what is the exact encryption algorithm, and how is the salt used?

**Comment by marnix** [comment]
Implemented this in pull request #25 which I just merged.  See those diffs / commits for what is new in version 3.0.
