### ISSUE TITLE
Update README.md with information on how to run the command line tool

### ISSUE THREAD

**Issue by robbinonline** [marnix/synology-decrypt#20]
Is there a wiki available how to get this script running.
My NAS drive crashes and all the data wat upload to a WebDAV now try to decrypt with the Synology tool but that crashes everytime.

Found this script but I have no idea how to run this exactly.
Someone here how can help me?

**Comment by marnix** [comment]
Unfortunately this script is not yet able to decrypt the recently introduced ("version 3.0") encrypted file format, so if your stuff has been recently uploaded by your Synology NAS, then you can only use Synology's own tool.

If that tool crashes on you, I'd advise you to contact Synology Support (currently at https://account.synology.com/support/): my experience with them so far has been quite good.

Now, you have a very valid point about how to run the tool-- this code was initially more intended as 'file format documentation' than as a practical tool. :-)

Still, I really should update the README.md file with how-to-run info.  But basically _it is a command line tool_, and running it comes down to the following:

* `git clone` this repository.
* Make sure you have Python installed (3.2 or later, or 2.7); Linux works, I've never tried it on Windows but that should also Just Work(tm).
* Install all Python packages which are mentioned in `requirements.txt`, e.g. by running `pip install -r requirements.txt`.
* In the root folder of the repository, run `python -m syndecrypt` followed by the supported command line arguments (leave out or add `-h` for usage information / help).

*Note* that currently this tool only can decrypt a single file at a time.  Run in some kind of loop to go over all files that need to be decrypted.

(And no, I won't be adding a Wiki for now.)

**Comment by dmerrick** [comment]
Thanks, this was exactly what I was looking for (specifically, `python -m syndecrypt`)

**Comment by marnix** [comment]
Added documentation, closing this issue.
