### ISSUE TITLE
Document dependency on lz4

### ISSUE THREAD

**Issue by mlangenberg** [marnix/synology-decrypt#22]
Took me a while to figure out this program requires the `lz4` to be available on my system.

The error message is non-descriptive if you aren't used to Python traces.

```
INFO: decrypting "/path/to/file" to "/tmp/path/to/file"
ERROR: decryption failed, exception occurred: <type 'exceptions.OSError'>: [Errno 2] No such file or directory
```

Obviously I tried all permutations for passing the input file, output file and private keys before diving into the code.

**Comment by marnix** [comment]
Added documentation, closing this issue.

If there are specific other scenarios where the error reported is hairy, please open a separate issue.

Thanks!
