### ISSUE TITLE
New 3.0 file decryption only works for plain text files

### ISSUE THREAD

**Issue by anojht** [marnix/synology-decrypt#28]
Hello, the changes you have merged for 3.0 decryption support only works for plain text files. Any other file format yields and invalid padding byte error. 

However, the pull request with changes introduced by @neepl works for 3.0 version regardless of file type.

**Comment by marnix** [comment]
@anojht Thanks for the report!  I will look into this, probably there is an encoding/decoding byte vs string mistake somewhere.  I should have taken the essence of @neepl 's PR, but something seems to have gone wrong.

**Comment by anojht** [comment]
@marnix Thanks! Please let me know if you need any help, I have a fork of your project with some changes that allow people to use a GUI to make things easier and with macOS support. 

I also want to tackle decryption not working on large files, I have a test 4GB video file in MKV format that fails to decrypt with error message: "size doesn't fit in an int", I would love to help you tackle this one as well. Thanks for all your hard work in reverse engineering the algorithm! 😄

**Comment by marnix** [comment]
@anojht Could you perhaps attach an example of a (preferably small) version 3.0 or 3.1 non-text file that results in an invalid padding byte error?

Because I've been trying to reproduce this issue (using password encryption, with the current 3.1 format) and things work fine.

Thanks in advance!

**Comment by marnix** [comment]
So I've reproduced at least the symptom `invalid padding byte`, and fixed it in #32.  Feel free to reopen with info / a test case if you still see issues.

Thanks!
