### ISSUE TITLE
Question on  _openssl_kdf

### ISSUE THREAD

**Issue by hooyao** [marnix/synology-decrypt#33]
Hello Marnix,
I have a question regarding the function '_openssl_kdf', the implementation skips pkcs5s1 part mentioned in the [post](https://security.stackexchange.com/questions/29106/openssl-recover-key-and-iv-by-passphrase/117654#117654)
With md5, the function derives different AES key and iv from `openssl enc`. 

Is this a variation Synology takes to simplify key derivation? Is there any Synology documentation that describes the kdf?

Many thanks for this tool. I'm trying to understand the details and replicating your code in .net core.

**Comment by marnix** [comment]
The only change I made, compared to that post, is to iterate 1000 times, for the salt-based encryption that is used in the v3 algorithm, see commit 1dbf62cb.

I think that "1000 times" is a Synology-specific choice.

I'm not sure how to replicate the exact same behavior using `openssl enc`.

The only official documentation that I've found (and I've asked Synology support) is https://global.download.synology.com/download/Document/Software/WhitePaper/Package/CloudSync/All/enu/Synology_Cloud_Sync_White_Paper-Based_on_DSM_6.1.pdf.  About the "user-defined primary key (password)", that document only says (in a diagram) that it is somehow used as input to "AES-256" encryption of "a randomly generated 256-bit key" or "Randomly-generated 32-byte session key".

So no, the key derivation function going from password to AES-256 key doesn't seem to be documented in any way (except in 'my' `_openssl_kdf()` function. :-)

**Comment by hooyao** [comment]
> The only change I made, compared to that post, is to iterate 1000 times, for the salt-based encryption that is used in the v3 algorithm, see commit [1dbf62c](https://github.com/marnix/synology-decrypt/commit/1dbf62cbeaa0469bfde91ed96c491421c5e56a12).
> 
> I think that "1000 times" is a Synology-specific choice.
> 
> I'm not sure how to replicate the exact same behavior using `openssl enc`.
> 
> The only official documentation that I've found (and I've asked Synology support) is https://global.download.synology.com/download/Document/Software/WhitePaper/Package/CloudSync/All/enu/Synology_Cloud_Sync_White_Paper-Based_on_DSM_6.1.pdf. About the "user-defined primary key (password)", that document only says (in a diagram) that it is somehow used as input to "AES-256" encryption of "a randomly generated 256-bit key" or "Randomly-generated 32-byte session key".
> 
> So no, the key derivation function going from password to AES-256 key doesn't seem to be documented in any way (except in 'my' `_openssl_kdf()` function. :-)

Thank you, Marnix for your clear and thorough explanation.
